<?php
/**
* Implementation of hook_commerce_customer_profile_type_info
*/
function student_show_customer_commerce_customer_profile_type_info() {
  $profile_types = array();

  $profile_types['student_info'] = array(
    'type' => 'student_info',
    'name' => t('Student Profile information'),
    'description' => t('The profile used to collect personal information on the checkout and order forms.'),
    'help' => '',
    'addressfield' => FALSE
  );

  return $profile_types;
}
