<?php

function student_show_customer_enable() {
  commerce_customer_configure_customer_profile_type('student_info');
  commerce_order_configure_customer_profile_type('student_info', 'Student Profile information');
}

/**
 * Update permission names for customer profile entity management.
 */
function student_show_customer_update_7005(&$sandbox) {
  commerce_customer_configure_customer_profile_type('student_info');
  commerce_order_configure_customer_profile_type('student_info', 'Student Profile information');
  $sandbox['#finished'] = TRUE;

  return t('Enabled fields on the commerce customer profile type: Student Profile information. Configured profile reference field on commerce_order');
}
